meta_product_name: "My To Do Manager"
meta_title: "My To Do Manager - Task list for everyday"
meta_description: "Task list for everyday"
meta_image: "completed-task.png"
twitter_account: "@leojdeveloper"